/**
 * Descrizioni in italiano degli export di src/, usate per generare docs/FUNCTIONS.md.
 * Chiave: "percorso#nome". Campi: s = scopo (se manca si usa il commento TSDoc del codice),
 * p = note su parametri e valore restituito, e = effetti collaterali (se manca vale quello del file
 * in FILE_EFFECTS). `npm run docs:check` segnala gli export senza scopo o senza effetti.
 */

export interface Description {
  s?: string
  p?: string
  e?: string
}

const PURE = 'Nessuno: funzione pura.'
const UI = 'Solo interfaccia: nessuna scrittura su Firestore né chiamata di rete.'

/** Effetti collaterali predefiniti per tutti gli export (non tipi) di un file. */
export const FILE_EFFECTS: Record<string, string> = {
  'src/lib/nutrition.ts': PURE,
  'src/lib/dates.ts': PURE,
  'src/lib/format.ts': PURE,
  'src/lib/text.ts': PURE,
  'src/lib/foodLibrary.ts': PURE,
  'src/lib/myFoodsSearch.ts': PURE,
  'src/lib/syncState.ts': PURE,
  'src/lib/foodSearch/display.ts': PURE,
  'src/lib/foodSearch/genericRanking.ts': PURE,
  'src/lib/foodSearch/queryText.ts': PURE,
  'src/lib/foodSearch/translate.ts': PURE,
  'src/lib/foodSearch/validate.ts': PURE,
  'src/lib/foodSearch/types.ts': PURE,
  'src/lib/foodSearch/genericSearch.ts': PURE,
  'src/features/history/stats.ts': PURE,
  'src/features/history/chartTheme.ts': PURE,
  'src/services/mappers.ts': PURE,
  'src/services/refs.ts': 'Nessuno: crea solo riferimenti Firestore (nessuna lettura o scrittura).',
  'src/components/ui/Button.tsx': UI,
  'src/components/ui/Card.tsx': UI,
  'src/components/ui/Feedback.tsx': UI,
  'src/components/ui/Fields.tsx': UI,
  'src/components/ui/Icons.tsx': UI,
  'src/components/ui/PendingMark.tsx': UI,
  'src/components/ui/Progress.tsx': UI,
  'src/components/ui/Spinner.tsx': UI,
  'src/components/layout/BottomNav.tsx': UI,
  'src/features/diary/DayNavigator.tsx': UI,
  'src/features/diary/DaySummary.tsx': UI,
  'src/features/diary/MealSection.tsx': UI,
  'src/features/diary/MealSelect.tsx': UI,
  'src/features/picker/FoodRow.tsx': UI,
  'src/features/picker/PortionForm.tsx': UI,
  'src/features/picker/ManualFoodForm.tsx': UI + ' Valida i valori e li passa a onSubmit.',
  'src/features/history/CaloriesChart.tsx': UI,
  'src/features/history/WeightChart.tsx': UI,
  'src/features/auth/ConfigMissing.tsx': UI,
}

export const DESCRIPTIONS: Record<string, Description> = {
  // ------------------------------------------------------------------ App
  'src/App.tsx#App': {
    s: 'Radice dell\'app (export di default): ErrorBoundary → ThemeProvider → (ConfigMissing se mancano le variabili Firebase) → AuthProvider → ToastProvider → Gate. Gate mostra il caricamento, LoginPage o, per l\'utente autenticato, SyncProvider + AuthenticatedApp (header con SyncIndicator, onboarding, schede, BottomNav).',
    e: 'AuthenticatedApp crea users/{uid} con createUserDoc quando il server conferma che non esiste; avvia usePendingScanCompletion; legge e scrive l\'hash dell\'URL tramite useHashTab.',
  },

  // ------------------------------------------------------------------ components/layout
  'src/components/layout/BottomNav.tsx#BottomNav': { s: 'Barra di navigazione fissa in basso con le quattro schede (Diario, Alimenti, Storico, Profilo).', p: 'tab: scheda attiva; onChange: chiamata con la scheda scelta.' },
  'src/components/layout/ErrorBoundary.tsx#ErrorBoundary': { s: 'Componente a classe che intercetta gli errori di rendering e mostra "Qualcosa è andato storto" con il pulsante "Ricarica l\'app".', e: 'Scrive l\'errore in console; il pulsante ricarica la pagina.' },
  'src/components/layout/SyncIndicator.tsx#SyncIndicator': { e: 'Solo interfaccia: legge lo stato da useSync.' },

  // ------------------------------------------------------------------ components/ui
  'src/components/ui/Button.tsx#Button': { s: 'Pulsante con varianti (primary, secondary, ghost, danger), dimensioni e stato loading (spinner, disattivato).' },
  'src/components/ui/Card.tsx#Card': { s: 'Contenitore con bordo arrotondato e sfondo, per raggruppare sezioni.' },
  'src/components/ui/Card.tsx#SectionTitle': { s: 'Titolo di sezione dentro una Card, con un\'azione facoltativa a destra.' },
  'src/components/ui/Feedback.tsx#ErrorNotice': { s: 'Riquadro d\'errore con titolo e messaggio leggibile (errorMessage).' },
  'src/components/ui/Feedback.tsx#EmptyState': { s: 'Stato vuoto con icona, titolo e testo facoltativo.' },
  'src/components/ui/Fields.tsx#TextField': { s: 'Campo di testo con etichetta, suggerimento e suffisso facoltativi.' },
  'src/components/ui/Fields.tsx#SelectField': { s: 'Menu a tendina con etichetta e suggerimento.' },
  'src/components/ui/Fields.tsx#Toggle': { s: 'Interruttore on/off con etichetta.' },
  'src/components/ui/Icons.tsx#BookIcon': { s: 'Icona SVG del libro (scheda Diario).' },
  'src/components/ui/Icons.tsx#AppleIcon': { s: 'Icona SVG della mela (scheda Alimenti).' },
  'src/components/ui/Icons.tsx#ChartIcon': { s: 'Icona SVG del grafico (scheda Storico).' },
  'src/components/ui/Icons.tsx#UserIcon': { s: 'Icona SVG dell\'utente (scheda Profilo).' },
  'src/components/ui/Icons.tsx#ChevronLeft': { s: 'Freccia a sinistra (giorno precedente).' },
  'src/components/ui/Icons.tsx#ChevronRight': { s: 'Freccia a destra (giorno successivo).' },
  'src/components/ui/Icons.tsx#PlusIcon': { s: 'Icona "+" per aggiungere.' },
  'src/components/ui/Icons.tsx#StarIcon': { s: 'Stella dei preferiti, piena o vuota (prop filled).' },
  'src/components/ui/Icons.tsx#BarcodeIcon': { s: 'Icona del codice a barre (apre lo scanner).' },
  'src/components/ui/Icons.tsx#SearchIcon': { s: 'Lente della ricerca.' },
  'src/components/ui/Progress.tsx#MacroBar': { s: 'Barra di avanzamento di un macronutriente (valore / obiettivo) con colore e etichetta.' },
  'src/components/ui/Sheet.tsx#Sheet': { e: 'Blocca lo scroll della pagina mentre è aperto, sposta il focus sul pannello e lo restituisce alla chiusura; ascolta Esc (chiude solo il pannello in primo piano). Usa un portal su document.body.' },
  'src/components/ui/Spinner.tsx#Spinner': { s: 'Indicatore di caricamento animato.' },
  'src/components/ui/Spinner.tsx#LoadingBlock': { s: 'Blocco centrato con spinner ed etichetta (predefinita "Caricamento…").' },

  // ------------------------------------------------------------------ contexts
  'src/contexts/AuthContext.tsx#AuthProvider': {
    s: 'Fornisce utente, stato di caricamento, errore, popupUnavailable, signIn e signOut. signIn avvia signInWithPopup in modo sincrono nel click (niente redirect) e classifica gli errori con classifySignInError.',
    e: 'Ascolta onAuthStateChanged; se l\'utente cambia o esce in un\'altra scheda (e questa non sta già uscendo) chiama wipeLocalDataAndReload. signIn apre il popup di Google; signOut esegue secureSignOut (logout, pulizia dei dati locali, ricarica).',
  },
  'src/contexts/AuthContext.tsx#useAuth': { s: 'Accesso al contesto di autenticazione (user, loading, error, popupUnavailable, signIn, signOut).', e: 'Nessuno. Lancia un errore se usato fuori da AuthProvider.' },
  'src/contexts/AuthContext.tsx#useUid': { e: 'Nessuno. Lancia un errore se non c\'è un utente autenticato.' },
  'src/contexts/SyncContext.tsx#SyncProvider': { e: 'Apre 6 listener onSnapshot con includeMetadataChanges (profilo, voci degli ultimi 90 giorni, ultime 50 voci, alimenti, pesi, codici in coda); dopo una sincronizzazione completa mostra "Tutto sincronizzato" per 4 secondi.' },
  'src/contexts/SyncContext.tsx#useSync': { s: 'Stato di sincronizzazione: online, pendingCount (modifiche in attesa) e state (offline, syncing, synced, online).', e: 'Nessuno. Lancia un errore se usato fuori da SyncProvider.' },
  'src/contexts/ThemeContext.tsx#ThemeProvider': { s: 'Gestisce la preferenza di tema (system, light, dark).', e: 'Salva la preferenza in localStorage ("theme"), aggiunge o toglie la classe dark su <html>, aggiorna meta theme-color, ascolta prefers-color-scheme.' },
  'src/contexts/ThemeContext.tsx#useTheme': { s: 'Legge e imposta il tema ({ theme, setTheme }).', e: 'Nessuno. Lancia un errore se usato fuori da ThemeProvider.' },
  'src/contexts/ToastContext.tsx#ToastProvider': { s: 'Notifiche temporanee in alto (al massimo 3): informative per 4 s, errori per 6 s, con azione facoltativa (es. "Annulla").', e: 'Timer per la chiusura automatica; reportError scrive anche in console.' },
  'src/contexts/ToastContext.tsx#useToast': { s: 'Restituisce notify(messaggio, azione?) e reportError(errore).', e: 'Nessuno. Lancia un errore se usato fuori da ToastProvider.' },

  // ------------------------------------------------------------------ features/account
  'src/features/account/AccountSection.tsx#AccountSection': { e: 'Al tocco su "Esci": online attende flushPendingWrites (15 s), offline chiede conferma con window.confirm; poi signOut (logout sicuro: cancella i dati locali e ricarica).' },
  'src/features/account/MyDataSection.tsx#MyDataSection': { e: 'Export: legge tutto con exportAllData (rete o cache) e scarica un JSON e un CSV. Eliminazione: deleteAllUserData (cancella i documenti su Firestore), deleteAuthAccount o reauthenticateAndDelete (popup Google), poi wipeLocalDataAndReload.' },
  'src/features/account/OnboardingPage.tsx#OnboardingPage': { e: 'Tramite ProfileForm salva il profilo con onboarded: true; "Salta per ora" chiama saveProfile con i valori attuali e onboarded: true.' },

  // ------------------------------------------------------------------ features/auth
  'src/features/auth/LoginPage.tsx#LoginPage': {
    s: 'Schermata di accesso: logo, "Accedi con Google", avvisi per offline, browser in-app (con "Copia link") e popup bloccato (con "Riprova"), errore di accesso.',
    e: 'Chiama signIn (popup di Google) direttamente nel click; "Copia link" scrive negli appunti (navigator.clipboard, altrimenti window.prompt).',
  },

  // ------------------------------------------------------------------ features/diary
  'src/features/diary/AddFoodSheet.tsx#AddFoodSheet': { e: 'Per ogni aggiunta: recordFoodUse (crea o aggiorna l\'alimento in users/{uid}/foods) e addEntry (nuova voce); le Promise non sono attese, gli errori vanno a reportError; notifica di conferma.' },
  'src/features/diary/DiaryPage.tsx#DiaryPage': { s: 'Pagina Diario: navigazione tra i giorni, riepilogo del giorno, i quattro pasti, invito a completare il profilo se manca; apre AddFoodSheet, EntryEditor e RecipeEditor ("Salva il pasto come ricetta").', e: 'Ascolta le voci del giorno con useDayEntries (listener Firestore).' },
  'src/features/diary/EntryEditor.tsx#EntryEditor': { e: 'updateEntry, deleteEntry (con "Annulla" che chiama restoreEntry) e, per le voci senza foodId, recordFoodUse con favorite: true.' },
  'src/features/diary/MealSection.tsx#MealSection': { s: 'Card di un pasto: icona, totali, pulsante +, elenco delle voci (con segno se non sincronizzate) e "Salva il pasto come ricetta" se ci sono almeno 2 voci.' },
  'src/features/diary/MealSelect.tsx#MealSelect': { s: 'Selettore del pasto (Colazione, Pranzo, Cena, Spuntini) basato su Segmented.' },

  // ------------------------------------------------------------------ features/foods
  'src/features/foods/FoodEditor.tsx#FoodEditor': { e: 'saveFood (crea o aggiorna; con codice a barre usa il codice come id) e deleteFood, dopo window.confirm.' },
  'src/features/foods/FoodsPage.tsx#FoodsPage': { s: 'Pagina Alimenti: "+ Alimento", "+ Ricetta", sezione "Da completare" (codici scansionati offline), filtro testuale e per tipo, elenco come "Nome - Marca" con preferiti.', e: 'Ascolta useFoods e usePendingScans; setFavorite e removePendingScan (non attese).' },
  'src/features/foods/RecipeEditor.tsx#RecipeEditor': { e: 'saveFood con kind: "recipe" e deleteFood (dopo conferma). Gli ingredienti si scelgono con FoodPicker (che può salvare alimenti tra i miei alimenti se scansionati o messi tra i preferiti).' },

  // ------------------------------------------------------------------ features/history
  'src/features/history/HistoryPage.tsx#HistoryPage': { s: 'Pagina Storico (export di default, caricata in modo lazy): periodo 7 o 30 giorni, media giornaliera, giorni registrati ed entro l\'obiettivo, grafico delle calorie, media settimanale, dati giornalieri e sezione del peso.', e: 'Ascolta useEntriesRange (listener Firestore).' },
  'src/features/history/WeightChart.tsx#WeightChart': { s: 'Grafico a linea del peso (recharts) con asse Y a passo intero.' },
  'src/features/history/WeightSection.tsx#WeightSection': { s: 'Sezione Peso: registrazione (data e kg), ultimo peso e variazione, grafico, elenco con eliminazione.', e: 'Ascolta useWeights; logWeight (anche aggiornamento del profilo se la data è oggi) e deleteWeight, non attese.' },
  'src/features/history/stats.ts#dailyTotals': {},
  'src/features/history/chartTheme.ts#axisProps': { s: 'Proprietà comuni degli assi dei grafici (colori dalle variabili CSS --chart-*).' },
  'src/features/history/chartTheme.ts#tooltipStyle': { s: 'Stile comune dei tooltip dei grafici.' },

  // ------------------------------------------------------------------ features/picker
  'src/features/picker/BarcodeScanner.tsx#BarcodeScanner': { e: 'Chiede l\'accesso alla fotocamera posteriore (getUserMedia), carica @zxing/browser con import dinamico, vibra alla lettura; ferma la fotocamera alla chiusura.' },
  'src/features/picker/FoodPicker.tsx#FoodPicker': { s: 'Scelta di un alimento con quattro schede: Cerca (SearchTab), Miei, Recenti, Manuale. onSelect apre la scelta della quantità; onDirect aggiunge subito con i grammi indicati.', e: 'Ascolta useFoods e useRecentFoods; setFavorite; nel modulo manuale con "Aggiungi ai preferiti" chiama recordFoodUse (favorite: true) prima di onDirect.' },
  'src/features/picker/SearchTab.tsx#SearchTab': {
    s: 'Ricerca alimenti e lettura dei codici a barre: sezioni "I miei alimenti", "Alimenti generici" (con prodotti trasformati espandibili) e "Prodotti confezionati", con stelle, errori per fonte, "Salva per dopo" e "Inserisci a mano".',
    e: 'Chiamate di rete a USDA e Open Food Facts (searchOnline, getProductByBarcode) con debounce di 500 ms e annullamento; cache delle ricerche; letture findSavedFood; scritture recordFoodUse, setFavorite e queuePendingScan (non attese).',
  },

  // ------------------------------------------------------------------ features/profile
  'src/features/profile/ExportSection.tsx#ExportSection': { e: 'Legge con fetchEntries e fetchWeights (getDocs) e scarica file CSV.' },
  'src/features/profile/ProfileForm.tsx#ProfileForm': { s: 'Modulo del profilo: sesso, età, altezza, peso, attività, obiettivo; mostra metabolismo basale, fabbisogno e obiettivo consigliato; obiettivo manuale; target dei macro con "Calcola"; "Crea profilo" o "Salva profilo".', e: 'saveProfile (con onboarded: true), non attesa; notifica "Profilo salvato"; chiama onSaved se presente.' },
  'src/features/profile/ProfilePage.tsx#ProfilePage': { s: 'Pagina Profilo: AccountSection, ProfileForm, tema e installazione dell\'app, ExportSection, MyDataSection, crediti Open Food Facts.', e: 'Cambia il tema (localStorage tramite ThemeProvider); "Installa" avvia il prompt di installazione del browser.' },

  // ------------------------------------------------------------------ hooks
  'src/hooks/data.ts#useProfile': { s: 'Listener sul documento users/{uid}: profilo (o null), loading, error, fromCache.', e: 'Listener onSnapshot (con metadati) finché il componente è montato.' },
  'src/hooks/data.ts#useDayEntries': { s: 'Voci del giorno indicato, ordinate per createdAt.', e: 'Listener onSnapshot su entries con date == giorno.' },
  'src/hooks/data.ts#useEntriesRange': { s: 'Voci in un intervallo di date, ordinate per data.', e: 'Listener onSnapshot su entries (date >= da, date <= a).' },
  'src/hooks/data.ts#useFoods': { s: 'I miei alimenti e ricette: preferiti prima, poi in ordine alfabetico.', e: 'Listener onSnapshot su foods ordinati per nome.' },
  'src/hooks/data.ts#useRecentFoods': { e: 'Listener onSnapshot sulle ultime 400 voci (orderBy createdAt desc).' },
  'src/hooks/data.ts#useWeights': { s: 'Pesi registrati in ordine di data.', e: 'Listener onSnapshot su weights.' },
  'src/hooks/data.ts#usePendingScans': { e: 'Listener onSnapshot su pendingScans.' },
  'src/hooks/useFirestore.ts#useQueryData': { e: 'Apre e chiude un listener onSnapshot (includeMetadataChanges) quando cambia la query.' },
  'src/hooks/useFirestore.ts#useDocData': { e: 'Apre e chiude un listener onSnapshot (includeMetadataChanges) quando cambia il riferimento.' },
  'src/hooks/useHashTab.ts#TABS': { s: 'Elenco delle schede: diario, alimenti, storico, profilo.', e: PURE },
  'src/hooks/useHashTab.ts#useHashTab': { e: 'Ascolta hashchange; setTab scrive window.location.hash e torna in cima alla pagina.' },
  'src/hooks/useInstallPrompt.ts#useInstallPrompt': { p: 'Restituisce una funzione install() oppure null se il browser non offre l\'installazione.', e: 'Ascolta beforeinstallprompt e appinstalled; install() mostra il prompt del browser.' },
  'src/hooks/useOnlineStatus.ts#useOnlineStatus': { s: 'true se il browser è online (navigator.onLine), aggiornato sugli eventi online e offline.', e: 'Ascolta gli eventi online e offline di window.' },
  'src/hooks/usePendingScanCompletion.ts#usePendingScanCompletion': { e: 'Quando l\'app è online e ci sono codici "pending": chiamate a Open Food Facts, recordFoodUse, removePendingScan o markPendingNotFound, notifiche.' },

  // ------------------------------------------------------------------ lib (varie)
  'src/lib/csv.ts#toCsv': { s: 'Crea un CSV con separatore ";" e virgola decimale (per Excel in italiano), con protezione dalla "CSV injection".', e: PURE },
  'src/lib/csv.ts#downloadCsv': { s: 'Scarica un CSV come file (con BOM UTF-8 per gli accenti in Excel).', e: 'Crea un Blob e un link temporaneo nel DOM e avvia il download.' },
  'src/lib/csv.ts#downloadJson': { s: 'Scarica dati come file JSON indentato.', e: 'Crea un Blob e un link temporaneo nel DOM e avvia il download.' },
  'src/lib/dates.ts#toDateKey': { s: 'Data → chiave locale "YYYY-MM-DD" (mai UTC).' },
  'src/lib/dates.ts#parseDateKey': { s: 'Chiave "YYYY-MM-DD" → Date a mezzanotte locale.' },
  'src/lib/dates.ts#todayKey': { s: 'Chiave del giorno corrente.', e: 'Nessuno (legge l\'orologio).' },
  'src/lib/dates.ts#addDays': { s: 'Aggiunge (o toglie) giorni a una chiave di data.' },
  'src/lib/dates.ts#isValidDateKey': { s: 'true se la stringa è una data valida in formato YYYY-MM-DD.' },
  'src/lib/dates.ts#formatDayLabel': { s: 'Etichetta del giorno: "Oggi", "Ieri", "Domani" o la data estesa in italiano.' },
  'src/lib/dates.ts#formatShortDate': { s: 'Data breve in italiano (es. "8 ott").' },
  'src/lib/firebase.ts#missingFirebaseKeys': { s: 'Nomi delle variabili Firebase obbligatorie mancanti (VITE_FIREBASE_API_KEY, _AUTH_DOMAIN, _PROJECT_ID, _APP_ID).', e: 'Nessuno.' },
  'src/lib/firebase.ts#isFirebaseConfigured': { s: 'true se tutte le variabili Firebase obbligatorie sono presenti.', e: 'Nessuno.' },
  'src/lib/firebase.ts#auth': { s: 'Istanza Firebase Auth creata con initializeAuth: persistenza localStorage, poi IndexedDB, poi sessionStorage; resolver per il popup; emulatore se VITE_USE_EMULATORS=true in sviluppo.', e: 'Inizializzata all\'import del modulo (solo se la configurazione è presente).' },
  'src/lib/firebase.ts#db': { s: 'Istanza Firestore con cache persistente IndexedDB e gestione multi-scheda (persistentLocalCache + persistentMultipleTabManager).', e: 'Inizializzata all\'import del modulo (solo se la configurazione è presente).' },
  'src/lib/firebase.ts#googleProvider': { s: 'Provider Google con prompt "select_account" (scelta dell\'account a ogni accesso), usato da signInWithPopup e reauthenticateWithPopup.', e: 'Nessuno.' },
  'src/lib/foodLibrary.ts#cleanBarcode': { s: 'Tiene solo le cifre; restituisce il codice se ha da 6 a 14 cifre, altrimenti null.' },
  'src/lib/foodLibrary.ts#foodTypeOf': { s: 'Tipo dell\'alimento salvato: recipe, packaged (Open Food Facts o con codice a barre), generic (USDA) o custom.' },
  'src/lib/format.ts#fmtInt': { s: 'Numero intero formattato in italiano (es. 1.234).' },
  'src/lib/format.ts#fmtDec': { s: 'Numero con al massimo un decimale, in italiano (es. 12,5).' },
  'src/lib/format.ts#fmtKcal': { s: 'Numero + " kcal". Non usato nel codice (vedi KNOWN_ISSUES).' },
  'src/lib/format.ts#fmtGrams': { s: 'Numero + " g". Non usato nel codice (vedi KNOWN_ISSUES).' },
  'src/lib/inAppBrowser.ts#detectInAppBrowser': { s: 'Riconosce dallo user agent i browser interni di WhatsApp, Instagram, Messenger, Facebook, TikTok, LINE, LinkedIn e le WebView Android/iOS (dove Google blocca il login). L\'app installata sulla schermata Home (standalone) non è considerata WebView.', p: 'ua: user agent; standalone: app installata. Restituisce { inApp, app }.', e: PURE },
  'src/lib/inAppBrowser.ts#currentInAppBrowser': { e: 'Nessuno (legge navigator.userAgent, navigator.standalone e matchMedia).' },
  'src/lib/inAppBrowser.ts#classifySignInError': { s: 'Classifica un errore di signInWithPopup: "ignore" (popup chiuso o annullato), "popup-unavailable" (popup bloccato o non supportato), "error" (tutto il resto).', e: PURE },
  'src/lib/localData.ts#APP_KEY_PREFIXES': { e: 'Nessuno.' },
  'src/lib/localData.ts#RUNTIME_CACHES': { e: 'Nessuno.' },
  'src/lib/localData.ts#clearLocalAppData': { s: 'Rimuove da localStorage e sessionStorage le chiavi con i prefissi dell\'app e di Firebase e cancella le cache del service worker con le risposte delle API; tiene il tema e i dati di altri siti sulla stessa origine.', p: 'env: archivi da pulire (iniettabili per i test). Restituisce le chiavi e le cache rimosse.', e: 'Cancella dati dal browser (Storage e CacheStorage).' },
  'src/lib/localData.ts#browserDataEnv': { e: 'Nessuno (raccoglie i riferimenti agli archivi, gestendo gli accessi bloccati).' },
  'src/lib/myFoodsSearch.ts#createMyFoodsSearch': { s: 'Crea la funzione di ricerca nei miei alimenti: indice Fuse.js su nome, marca e codice (normalizzati); prima chi contiene tutte le parole o il prefisso del codice, poi le corrispondenze approssimate; ogni gruppo ordinato per usageScore.', p: 'foods: lista dei miei alimenti; now: istante di riferimento. Restituisce search(query, limit = 8).' },
  'src/lib/nutrition.ts#MEALS': { s: 'Pasti con etichetta e icona: Colazione, Pranzo, Cena, Spuntini.' },
  'src/lib/nutrition.ts#mealLabel': { s: 'Etichetta italiana di un pasto.' },
  'src/lib/nutrition.ts#ACTIVITY_LEVELS': { s: 'Livelli di attività con etichetta, suggerimento e fattore (1,2 · 1,375 · 1,55 · 1,725 · 1,9).' },
  'src/lib/nutrition.ts#GOALS': { s: 'Obiettivi con variazione di kcal (−500, 0, +300) e proteine in g/kg (2,0, 1,6, 1,8).' },
  'src/lib/nutrition.ts#ZERO': { s: 'Valori nutrizionali a zero.' },
  'src/lib/nutrition.ts#round': { s: 'Arrotonda a un numero di decimali (predefinito 0).' },
  'src/lib/nutrition.ts#sumNutrients': { s: 'Somma i valori nutrizionali (kcal intere, macro a un decimale).' },
  'src/lib/pendingScanQueue.ts#completePendingScans': { p: 'items: codici in coda; deps: lookup, save, markNotFound, remove, notify (iniettati per i test). Restituisce { completed, notFound, retryLater }.', e: 'Solo tramite le dipendenze iniettate: chiamate di rete (lookup) e scritture (save, remove, markNotFound), notifiche.' },
  'src/lib/syncState.ts#syncState': { s: 'Stato da mostrare: offline, syncing (modifiche in attesa), synced (appena sincronizzato) oppure online.' },
  'src/lib/syncState.ts#syncLabel': { s: 'Testo dell\'indicatore: "Offline", "Offline · N modifiche in attesa", "Sincronizzazione in corso (N modifiche in attesa)", "Tutto sincronizzato", "Online".' },
  'src/lib/text.ts#matches': { s: 'true se il testo contiene la query, ignorando accenti e maiuscole.' },

  // ------------------------------------------------------------------ lib/foodSearch
  'src/lib/foodSearch/cache.ts#cacheKey': { s: 'Chiave di cache di una query: minuscolo, spazi compattati.', e: PURE },
  'src/lib/foodSearch/cache.ts#createSearchCache': { p: 'opzioni: ttlMs (24 h), storage (sessionStorage o null), now. Restituisce { get(query), set(query, valore) }.', e: 'Legge e scrive sessionStorage con il prefisso contacalorie:food-search:v2: (gli errori di archiviazione sono ignorati).' },
  'src/lib/foodSearch/display.ts#DISPLAY_CATEGORIES': {},
  'src/lib/foodSearch/queryText.ts#canonicalTokens': { s: 'Parole della query in forma canonica (queryTokens + canonical): singolare e plurale coincidono.' },
  'src/lib/foodSearch/display.ts#isStateDetail': { s: 'true se il dettaglio è uno stato di cottura o conservazione riconosciuto.' },
  'src/lib/foodSearch/genericRanking.ts#TIER': {},
  'src/lib/foodSearch/genericSearch.ts#GENERIC_DATASET': {},
  'src/lib/foodSearch/genericSearch.ts#displayOf': { s: 'Nome strutturato (GenericFoodDisplay) di una voce del dataset.' },
  'src/lib/foodSearch/genericSearch.ts#genericToResult': { s: 'Converte una voce del dataset in FoodResult (id "gen:<id>", nome formattato, porzioni, sinonimi, isPrimitive).' },
  'src/lib/foodSearch/genericSearch.ts#createGenericSearch': { p: 'foods: voci del dataset. Restituisce search(query, limit = 40).' },
  'src/lib/foodSearch/http.ts#HttpError': { e: 'Nessuno.' },
  'src/lib/foodSearch/http.ts#TimeoutError': { e: 'Nessuno.' },
  'src/lib/foodSearch/http.ts#NetworkError': { e: 'Nessuno.' },
  'src/lib/foodSearch/http.ts#DEFAULT_TIMEOUT_MS': { s: 'Timeout predefinito di ogni tentativo: 8000 ms.', e: 'Nessuno.' },
  'src/lib/foodSearch/http.ts#DEFAULT_RETRIES': { s: 'Ritentativi predefiniti: 2.', e: 'Nessuno.' },
  'src/lib/foodSearch/http.ts#DEFAULT_BASE_DELAY_MS': { s: 'Attesa prima del primo ritentativo: 500 ms (raddoppia a ogni tentativo).', e: 'Nessuno.' },
  'src/lib/foodSearch/http.ts#isAbortError': { s: 'true se l\'errore è un annullamento (AbortError).', e: PURE },
  'src/lib/foodSearch/http.ts#wait': { s: 'Attende un certo tempo, interrompibile con un AbortSignal.', e: 'Timer.' },
  'src/lib/foodSearch/http.ts#fetchJson': { p: 'url; opzioni: signal, timeoutMs, retries, baseDelayMs, retryNetworkErrors, allow404. Restituisce il JSON (o null per il 404 se allow404).', e: 'Richiesta HTTP GET (fetch) con timeout per tentativo e ritentativi su 5xx, 429, timeout (e errori di rete se richiesto). Lancia HttpError, TimeoutError, NetworkError o AbortError.' },
  'src/lib/foodSearch/index.ts#PACKAGED_SOURCES': { s: 'Fonti dei prodotti confezionati, in ordine: Search-a-licious, poi la ricerca classica di Open Food Facts.', e: 'Nessuno.' },
  'src/lib/foodSearch/index.ts#SourcesFailedError': { e: 'Nessuno.' },
  'src/lib/foodSearch/index.ts#AllSourcesFailedError': { e: 'Nessuno.' },
  'src/lib/foodSearch/index.ts#OfflineError': { s: 'Errore "Sei offline": la ricerca online non è disponibile.', e: 'Nessuno.' },
  'src/lib/foodSearch/index.ts#searchPackaged': { p: 'query; opzioni: signal, cache, sources. Restituisce i risultati, [] se nessuna fonte trova nulla.', e: 'Rete (Open Food Facts) e cache delle ricerche (chiave "off|query"). Lancia OfflineError se offline, SourcesFailedError se tutte le fonti falliscono.' },
  'src/lib/foodSearch/index.ts#searchUsdaLive': { p: 'query; opzioni: signal, cache, search. Restituisce i risultati USDA tradotti.', e: 'Rete (USDA) e cache delle ricerche (chiave "usda|query"). Lancia OfflineError se offline.' },
  'src/lib/foodSearch/index.ts#searchOnline': { p: 'query; opzioni: includeUsda (predefinito true), signal, cache, usdaSearch, packagedSources. Restituisce { usda, packaged, usdaError, packagedError, usdaSkipped }.', e: 'Rete verso USDA e Open Food Facts in parallelo; rilancia solo gli AbortError.' },
  'src/lib/foodSearch/index.ts#mergeGeneric': { e: PURE },
  'src/lib/foodSearch/index.ts#allSourcesFailed': { e: PURE },
  'src/lib/foodSearch/index.ts#resultToItem': { p: 'Restituisce un FoodItem con per100, defaultGrams (porzione del produttore o 100), porzioni, servingGrams e key (id del risultato reso valido come id di documento).', e: PURE },
  'src/lib/foodSearch/openFoodFacts.ts#offProductToResult': { e: PURE },
  'src/lib/foodSearch/openFoodFacts.ts#searchSearchalicious': { e: 'Rete: GET search.openfoodfacts.org (20 risultati, lingue it ed en).' },
  'src/lib/foodSearch/openFoodFacts.ts#searchOffLegacy': { e: 'Rete: GET it.openfoodfacts.org/cgi/search.pl, ritentando anche gli errori di rete.' },
  'src/lib/foodSearch/openFoodFacts.ts#getProductByBarcode': { e: 'Rete: GET world.openfoodfacts.org/api/v2/product/{codice}.json (404 → null, ritenta gli errori di rete).' },
  'src/lib/foodSearch/translate.ts#DICTIONARY_SIZE': {},
  'src/lib/foodSearch/types.ts#SOURCE_LABEL': { s: 'Nomi leggibili delle fonti esterne (Open Food Facts, USDA). Riesportato dall\'index ma non usato nell\'interfaccia.' },
  'src/lib/foodSearch/usda.ts#USDA_API_KEY': { e: 'Nessuno (letta da VITE_USDA_API_KEY, altrimenti "DEMO_KEY").' },
  'src/lib/foodSearch/usda.ts#searchUsda': { e: 'Rete: GET api.nal.usda.gov/fdc/v1/foods/search (15 risultati, Foundation e SR Legacy).' },
  'src/lib/foodSearch/usdaMap.ts#USDA_SEARCH_URL': { s: 'URL dell\'endpoint di ricerca di USDA FoodData Central.', e: 'Nessuno.' },
  'src/lib/foodSearch/usdaMap.ts#USDA_DATA_TYPES': { s: 'Dataset USDA interrogati: "Foundation,SR Legacy".', e: 'Nessuno.' },
  'src/lib/foodSearch/usdaMap.ts#usdaNutrients': { e: PURE },
  'src/lib/foodSearch/usdaMap.ts#usdaFoodToResult': { e: 'Nessuno, a parte il conteggio dei token non tradotti in usdaToItalian.' },
  'src/lib/foodSearch/usdaToItalian.ts#mapFoodCategory': { s: 'Categoria USDA (es. "Fruits and Fruit Juices") → categoria italiana, oppure null.', e: PURE },
  'src/lib/foodSearch/usdaToItalian.ts#tokenize': { s: 'Divide una descrizione USDA in token (virgole), ignorando il testo tra parentesi e togliendo i marchi noti.', e: PURE },
  'src/lib/foodSearch/usdaToItalian.ts#inflect': { e: PURE },
  'src/lib/foodSearch/usdaToItalian.ts#untranslatedReport': { e: 'Nessuno (legge il registro interno dei token non tradotti).' },
  'src/lib/foodSearch/usdaToItalian.ts#resetUntranslated': { s: 'Svuota il registro dei token non tradotti (usato nei test).', e: 'Modifica il registro interno al modulo.' },
  'src/lib/foodSearch/usdaToItalian.ts#usdaToItalian': { p: 'description: descrizione USDA; foodCategory: categoria USDA facoltativa. Restituisce { display, isPrimitive } o null.', e: 'Registra i token sconosciuti nel registro interno; in sviluppo (import.meta.env.DEV) li scrive in console.' },

  // ------------------------------------------------------------------ services
  'src/services/account.ts#exportAllData': { p: 'uid; user: email e displayName. Restituisce { exportedAt, account, profile, entries, foods, weights, pendingScans } senza il campo locale pending.', e: 'Letture Firestore: getDoc del profilo e getDocs di tutte le sottocollezioni.' },
  'src/services/account.ts#deleteAllUserData': { p: 'Restituisce il numero di documenti cancellati.', e: 'getDocs e writeBatch delete (a blocchi di 400) su entries, foods, weights e pendingScans, poi deleteDoc del profilo. Richiede la rete; irreversibile.' },
  'src/services/account.ts#needsRecentLogin': { s: 'true se l\'errore è auth/requires-recent-login.', e: PURE },
  'src/services/account.ts#deleteAuthAccount': { e: 'deleteUser su Firebase Authentication (irreversibile).' },
  'src/services/account.ts#reauthenticateAndDelete': { e: 'Apre il popup Google (reauthenticateWithPopup), poi deleteUser.' },
  'src/services/entries.ts#addEntry': { s: 'Crea una voce di diario con id generato sul dispositivo (o con l\'id indicato) e valori calcolati per i grammi.', p: 'uid, date, mealType, item (FoodItem), grams, id facoltativo. Restituisce la Promise di setDoc (si risolve solo alla conferma del server: non attenderla nell\'interfaccia).', e: 'setDoc su users/{uid}/entries con createdAt = serverTimestamp().' },
  'src/services/entries.ts#restoreEntry': { e: 'setDoc della voce con lo stesso id (il createdAt viene rigenerato).' },
  'src/services/entries.ts#entryToItem': { s: 'Converte una voce in FoodItem (per modificarla o riaggiungerla).', e: PURE },
  'src/services/entries.ts#updateEntry': { s: 'Cambia grammi, pasto o giorno di una voce e ricalcola kcal e macro da per100.', e: 'updateDoc con updatedAt = serverTimestamp().' },
  'src/services/entries.ts#deleteEntry': { s: 'Elimina una voce.', e: 'deleteDoc.' },
  'src/services/entries.ts#fetchEntries': { e: 'Lettura Firestore con getDocs (usa la cache se offline).' },
  'src/services/foods.ts#saveFood': { p: 'uid; data: campi dell\'editor; id facoltativo (se presente aggiorna). Restituisce subito { id, done }.', e: 'Con id: updateDoc. Senza: setDoc con id uguale al codice a barre (se valido) o generato, più source, type, origin, useCount 0, lastUsedAt e createdAt.' },
  'src/services/foods.ts#recordFoodUse': { p: 'uid; item: FoodItem; opts: { origin, countUse, favorite? }. Restituisce subito { id, done } (id = foodKey, da usare come foodId della voce).', e: 'getDocFromCache per sapere se esiste; poi setDoc (nuovo alimento) oppure updateDoc con lastUsedAt, useCount = increment(1) e favorite (se richiesto).' },
  'src/services/foods.ts#setFavorite': { s: 'Mette o toglie un alimento dai preferiti.', e: 'updateDoc di favorite e updatedAt.' },
  'src/services/foods.ts#deleteFood': { s: 'Elimina un alimento o una ricetta (le voci del diario non cambiano).', e: 'deleteDoc.' },
  'src/services/foods.ts#foodToItem': { s: 'Converte un alimento salvato in FoodItem (foodId = id del documento; source "recipe" per le ricette).', e: PURE },
  'src/services/foods.ts#findSavedFood': { e: 'getDocFromCache, poi getDoc dal server se online (gli errori diventano null).' },
  'src/services/mappers.ts#toEntry': { s: 'Documento Firestore → Entry, con valori predefiniti sicuri e pending = metadata.hasPendingWrites.' },
  'src/services/mappers.ts#toFood': { s: 'Documento → Food; per i documenti vecchi deduce source, type, origin, lastUsedAt e useCount.' },
  'src/services/mappers.ts#toPendingScan': { s: 'Documento → PendingScan (barcode = id del documento).' },
  'src/services/mappers.ts#toWeight': { s: 'Documento → WeightEntry (date = id del documento).' },
  'src/services/mappers.ts#DEFAULT_PROFILE': { s: 'Profilo predefinito (uomo, 30 anni, 175 cm, 75 kg, moderato, mantenere, 2000 kcal, onboarded false), usato finché l\'utente non salva il proprio.' },
  'src/services/mappers.ts#toProfile': { s: 'Documento → Profile (null se non esiste); onboarded vale true se il campo manca.' },
  'src/services/pendingScans.ts#queuePendingScan': { e: 'setDoc su users/{uid}/pendingScans/{codice} con status "pending".' },
  'src/services/pendingScans.ts#markPendingNotFound': { s: 'Segna un codice in coda come non trovato su Open Food Facts.', e: 'updateDoc con status "not_found".' },
  'src/services/pendingScans.ts#removePendingScan': { s: 'Toglie un codice dalla coda.', e: 'deleteDoc.' },
  'src/services/profile.ts#saveProfile': { s: 'Salva il profilo (unione con i campi esistenti).', e: 'setDoc con merge e updatedAt = serverTimestamp().' },
  'src/services/profile.ts#createUserDoc': { e: 'setDoc del profilo base (DEFAULT_PROFILE, displayName, onboarded false, createdAt, updatedAt).' },
  'src/services/refs.ts#userRef': { s: 'Riferimento al documento users/{uid}.' },
  'src/services/refs.ts#entriesRef': { s: 'Riferimento alla collezione users/{uid}/entries.' },
  'src/services/refs.ts#foodsRef': { s: 'Riferimento alla collezione users/{uid}/foods.' },
  'src/services/refs.ts#weightsRef': { s: 'Riferimento alla collezione users/{uid}/weights.' },
  'src/services/refs.ts#pendingScansRef': { s: 'Riferimento alla collezione users/{uid}/pendingScans.' },
  'src/services/session.ts#isLeaving': { e: 'Nessuno.' },
  'src/services/session.ts#flushPendingWrites': { p: 'timeoutMs (predefinito 15000). Restituisce true se tutte le scritture sono state confermate in tempo.', e: 'waitForPendingWrites su Firestore.' },
  'src/services/session.ts#wipeLocalDataAndReload': { e: 'terminate(db), clearIndexedDbPersistence (fino a 5 tentativi), clearLocalAppData, poi location.replace senza hash (ricarica sul Diario).' },
  'src/services/session.ts#secureSignOut': { e: 'signOut di Firebase Auth, poi wipeLocalDataAndReload.' },
  'src/services/weights.ts#logWeight': { p: 'uid, date, kg, profile (o null). Restituisce la Promise di tutte le scritture.', e: 'setDoc su users/{uid}/weights/{data}; se la data è oggi e c\'è un profilo, saveProfile con weightKg e kcalTarget ricalcolato (se non manuale).' },
  'src/services/weights.ts#deleteWeight': { s: 'Elimina il peso di un giorno.', e: 'deleteDoc.' },
  'src/services/weights.ts#fetchWeights': { s: 'Tutti i pesi in ordine di data (per l\'esportazione).', e: 'Lettura Firestore con getDocs.' },

  // ------------------------------------------------------------------ tipi senza commento
  'src/contexts/ThemeContext.tsx#ThemePref': { s: 'Preferenza di tema: "system", "light" o "dark".' },
  'src/features/history/CaloriesChart.tsx#DayPoint': { s: 'Punto del grafico delle calorie: data e kcal.' },
  'src/features/history/stats.ts#DayTotals': { s: 'Totali di un giorno con il flag logged (giorno con almeno una voce).' },
  'src/features/picker/FoodPicker.tsx#FoodPickerProps': { s: 'Proprietà di FoodPicker: onSelect, onDirect, manualSubmitLabel.' },
  'src/hooks/useHashTab.ts#Tab': { s: 'Nome di una scheda: "diario", "alimenti", "storico", "profilo".' },
  'src/lib/csv.ts#CsvCell': { s: 'Valore di una cella CSV: testo, numero, null o undefined.' },
  'src/lib/foodLibrary.ts#FoodWrite': { s: 'Piano di scrittura di un alimento: "create" con i dati oppure "touch" (aggiorna utilizzo e/o preferito).' },
  'src/lib/foodLibrary.ts#FoodUseOptions': { s: 'Opzioni di recordFoodUse e planFoodWrite: origin, countUse, favorite.' },
  'src/lib/foodSearch/cache.ts#CachedSearch': { s: 'Valore in cache: risultati e fonte.' },
  'src/lib/foodSearch/cache.ts#SearchCacheOptions': { s: 'Opzioni di createSearchCache: ttlMs, storage, now.' },
  'src/lib/foodSearch/cache.ts#SearchCache': { s: 'Tipo della cache restituita da createSearchCache.' },
  'src/lib/foodSearch/display.ts#DisplayCategory': { s: 'Una delle categorie di DISPLAY_CATEGORIES.' },
  'src/lib/foodSearch/genericRanking.ts#RankedGeneric': { s: 'Risultato di rankGenericResults: main (in ordine) e processed (trasformati non richiesti).' },
  'src/lib/foodSearch/genericTypes.ts#GenericFoodsDataset': { s: 'Struttura di genericFoods.it.json: generatedAt, source, dataTypes, count, foods.' },
  'src/lib/foodSearch/http.ts#FetchJsonOptions': { s: 'Opzioni di fetchJson: signal, timeoutMs, retries, baseDelayMs, retryNetworkErrors, allow404.' },
  'src/lib/foodSearch/index.ts#PackagedSource': { s: 'Fonte di prodotti confezionati: nome e funzione search(query, signal).' },
  'src/lib/foodSearch/index.ts#SourceFailure': { s: 'Fonte fallita: nome ed errore.' },
  'src/lib/foodSearch/index.ts#OnlineOutcome': { s: 'Esito di searchOnline: risultati e errori di USDA e Open Food Facts, usdaSkipped.' },
  'src/lib/foodSearch/index.ts#OnlineOptions': { s: 'Opzioni di searchOnline.' },
  'src/lib/foodSearch/openFoodFacts.ts#OffProduct': { s: 'Prodotto come restituito da Open Food Facts (nome, marche, nutrienti, porzione, immagine).' },
  'src/lib/foodSearch/usdaMap.ts#UsdaNutrient': { s: 'Nutriente di una voce USDA (id, numero, nome, unità, valore).' },
  'src/lib/foodSearch/usdaMap.ts#UsdaFood': { s: 'Voce restituita dalla ricerca USDA: fdcId, descrizione, dataset, categoria e nutrienti.' },
  'src/lib/foodSearch/usdaToItalian.ts#UsdaTranslation': { s: 'Esito di usdaToItalian: display e isPrimitive.' },
  'src/lib/inAppBrowser.ts#InAppBrowser': { s: 'Esito di detectInAppBrowser: inApp e nome dell\'app (o "WebView").' },
  'src/lib/localData.ts#LocalDataEnv': { s: 'Archivi da pulire: localStorage, sessionStorage, CacheStorage (ognuno facoltativo).' },
  'src/lib/pendingScanQueue.ts#PendingScanDeps': { s: 'Dipendenze iniettate in completePendingScans: lookup, save, markNotFound, remove, notify.' },
  'src/lib/pendingScanQueue.ts#PendingScanOutcome': { s: 'Esito di completePendingScans: completed, notFound, retryLater.' },
  'src/types.ts#MealType': { s: 'Pasto: "breakfast", "lunch", "dinner", "snack".' },
  'src/types.ts#Nutrients': { s: 'kcal, protein, carbs, fat.' },
  'src/types.ts#Sex': { s: '"male" o "female".' },
  'src/types.ts#ActivityLevel': { s: 'Livello di attività: sedentary, light, moderate, active, very_active.' },
  'src/types.ts#Goal': { s: 'Obiettivo: lose, maintain, gain.' },
  'src/types.ts#RecipeIngredient': { s: 'Ingrediente di una ricetta: nome, grammi, valori per 100 g.' },
}
